version: "3.8"

services:
  postgres-mono:
    image: postgres:latest
    container_name: postgres_db_mono
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "6432:5432"
    volumes:
      - postgres_data_mono:/var/lib/postgresql/data
    networks:
      - devnet

  hourly-monolith-app:
    image: ghcr.io/goldenplayer5630/hourly-monolith-app:pre-release
    container_name: hourly-monolith-app
    ports:
      - "3001:80"
    networks:
      - devnet
    depends_on:
      - hourly-monolith

  hourly-monolith:
    image: ghcr.io/goldenplayer5630/hourly-monolith:pre-release
    container_name: hourly-monolith
    ports:
      - "5001:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres-mono;Port=6432;Database=hourly-timetrackingservice;Username=admin;Password=admin123"
      Logging__LogLevel__Default: Information
      Logging__LogLevel__Microsoft.AspNetCore: Warning
      CORS__AllowedOrigins: '["https://hourly-mono.vincentbok.nl"]'
      CORS__AllowedMethods: '["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]'
      CORS__AllowedHeaders: '["Content-Type", "Authorization"]'
      CORS__ExposedHeaders: '["X-Total-Count"]'
      CORS__AllowCredentials: "true"
      CORS__MaxAge: "3600"
    networks:
      - devnet
    depends_on:
      - postgres-mono

volumes:
  postgres_data_mono:

networks:
  devnet:
