version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "6432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - devnet

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5051:80"
    depends_on:
      - postgres
    networks:
      - devnet

  hourly-monolith:
    image: hourly-monolith:latest
    container_name: hourly-monolith
    build:
      context: .
      dockerfile: Hourly.Api/Dockerfile
    ports:
      - "5001:8080"
    environment:
      OCELOT__USER_SERVICE_HOST: userservice
      OCELOT__USER_SERVICE_PORT: 8080
      OCELOT__TIMETRACKING_SERVICE_HOST: timetracking
      OCELOT__TIMETRACKING_SERVICE_PORT: 8080
      OCELOT__GIT_SERVICE_HOST: gitservice
      OCELOT__GIT_SERVICE_PORT: 8080
      OCELOT__HTTP_TRANSPORT_SCHEME: "http"
    depends_on:
      - userservice
      - timetracking
      - gitservice
      - rabbitmq
    networks:
      - devnet

volumes:
  postgres_data:

networks:
  devnet:
