<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Hourly.Abstractions\Hourly.Abstractions.csproj" />
      <ProjectReference Include="..\Hourly.Domain\Hourly.Domain.csproj" />
      <ProjectReference Include="..\Hourly.Shared\Hourly.Shared.csproj" />
    </ItemGroup>

</Project>
